# Use the official Python image
FROM python:3.10-slim

# Set the directory in the container
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your code
COPY . .

# Run the web service on container startup
# Cloud Run expects the app to listen on the port defined by the PORT env var
CMD exec uvicorn main:app --host 0.0.0.0 --port $PORT